"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "app"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "webapp"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "helm":
      "parameters":
      - "name": "backend.frontendURL"
        "value": "http://frontend-service:3000"
      - "name": "backend.image.tag"
        "value": "ci-31eb576ea48ebfcd5997f5ca464607da667c26cc"
      - "name": "backend.service.port"
        "value": "5000"
      - "name": "backend.serviceName"
        "value": "backend-service"
      - "name": "frontend.backendURL"
        "value": "http://backend-service:5000"
      - "name": "frontend.image.tag"
        "value": "ci-796154666a25eb50ebdf01e305562ffd74e1f994"
      - "name": "frontend.ingress.enabled"
        "value": "true"
      - "name": "frontend.ingress.host"
        "value": "weather.com"
      - "name": "frontend.ingress.path"
        "value": "/"
      - "name": "frontend.service.port"
        "value": "3000"
      - "name": "frontend.service.type"
        "value": "LoadBalancer"
      - "name": "frontend.serviceName"
        "value": "frontend-service"
    "path": "charts/app"
    "repoURL": "https://github.com/valle-dei-mulini/infrastructure"
    "targetRevision": "HEAD"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "syncOptions":
    - "CreateNamespace=true"
