"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "ingress-nginx"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "ingress-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "ingress-nginx"
    "helm":
      "parameters":
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-additional-resource-tags"
        "value": "environment=dev,project=VALLEDEIMULINI"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-backend-protocol"
        "value": "http"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert"
        "value": "arn:aws:acm:eu-central-1:641456973426:certificate/e328a4f0-3998-48c4-a142-fdf91a5376bc"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-ports"
        "value": "https"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
        "value": "nlb"
      - "name": "controller.service.targetPorts.http"
        "value": "http"
      - "name": "controller.service.targetPorts.https"
        "value": "http"
      - "name": "rbac.create"
        "value": "true"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://kubernetes.github.io/ingress-nginx"
    "targetRevision": "2.16.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
